version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: elearning-postgres
    environment:
      POSTGRES_USER: elearning
      POSTGRES_PASSWORD: elearning123
      POSTGRES_DB: elearning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elearning"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - elearning-network

  redis:
    image: redis:7-alpine
    container_name: elearning-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - elearning-network

  adminer:
    image: adminer
    container_name: elearning-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - elearning-network

volumes:
  postgres_data:
  redis_data:

networks:
  elearning-network:
    driver: bridge
